apiVersion: v1
kind: ConfigMap
metadata:
  name: healthcare-api-config
  namespace: healthcare-api
  labels:
    app: healthcare-api
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  PORT: "8080"
  ALLOWED_ORIGINS: "https://yourdomain.com,https://app.yourdomain.com"
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_RPM: "100"
  DEFAULT_PAGE_SIZE: "10"
  MAX_PAGE_SIZE: "100"
  HEALTH_CHECK_PATH: "/health"